// GeneratedConstraintTests.cpp
// AUTO-GENERATED — do not edit by hand.
// Re-generate with: python scripts/generate_constraint_tests.py
//
// Source: C:\Users\jkino\Desktop\SRD Testing Files\output files from SRD Parser\out.json
//
// Tests every constraint in out.json against the six pure checker functions
// in ConstraintChecks.hpp.  Cases are derived mechanically from the constraint
// fields themselves: if a constraint has min=255, we test that FL254 fails and
// FL255 passes.  No flight plan simulation required.
//
// Dead-combination detection: cases tagged [DEAD_COMBO] assert that the
// destination check returns false even for a dest explicitly listed in 'dests',
// because nodests=["EG","EI"] blocks it first.  These expose every constraint
// in the dataset where the dests field can never fire.

#include <gtest/gtest.h>
#include "ConstraintChecks.hpp"
#include "rapidjson/document.h"

using namespace ConstraintChecks;

// ── Helpers ───────────────────────────────────────────────────────────────────

static std::vector<std::string> sv(std::initializer_list<const char*> il) {
    std::vector<std::string> v;
    for (auto s : il) v.push_back(s);
    return v;
}

#define PARSE(var, literal) \
    rapidjson::Document var; \
    var.Parse<rapidjson::kParseDefaultFlags>(literal)

// ── Alerts ───────────────────────────────────────────────────────────────────

struct AlertCase { const char* id; const char* json; bool expPass; bool expWarn; };
class AlertTest : public ::testing::TestWithParam<AlertCase> {};

TEST_P(AlertTest, Check) {
    const auto& p = GetParam();
    PARSE(doc, p.json);
    bool warn = false;
    EXPECT_EQ(p.expPass, checkOneAlerts(doc, warn)) << p.id;
    EXPECT_EQ(p.expWarn, warn) << p.id << " (warn flag)";
}

INSTANTIATE_TEST_SUITE_P(Generated, AlertTest, ::testing::Values(
    AlertCase{"EGVN_C61_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EGAA"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 PENIL L10 IOM NELBO P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C62_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EGPE"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 TLA GOW N560 NESDI GUSSI INS"]})", true, false},
    AlertCase{"EGVN_C63_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P16 RIBEL"]})", true, false},
    AlertCase{"EGVN_C64_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EGPH"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P16 RIBEL N601 INPIP"]})", true, false},
    AlertCase{"EGVN_C65_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 LELDO M145 BAGSO"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C66_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 LELDO M145 BAGSO"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGVN_C67_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 PENIL L70 BAGSO"]})", true, false},
    AlertCase{"EGVN_C68_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C69_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["DTY Y53 SAPCO N57 TNT L28 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGVN_C70_alerts", R"({"dir":"even","min":195,"max":245,"nodests":["EG","EI"],"points":["ORTAV"],"route":["KISWO N864 AVTIC N38 NOKIN P16 RIBEL N601 TLA GOW STN","KISWO N864 AVTIC N38 NOKIN P17 POL N601 TLA GOW STN"]})", true, false},
    AlertCase{"EGVN_C71_alerts", R"({"dir":"even","min":285,"nodests":["EG","EI"],"points":["ATSIX"],"route":["KISWO AVTIC ANJAK N38 NOKIN UP16 RIBEL UN601 TLA"]})", true, false},
    AlertCase{"EGVN_C72_alerts", R"({"dir":"even","min":285,"nodests":["EG","EI"],"points":["MATIK"],"route":["KISWO AVTIC ANJAK N38 NOKIN UP16 RIBEL UN601 TLA BESGA"]})", true, false},
    AlertCase{"EGVN_C73_alerts", R"({"dir":"even","min":255,"max":195,"nodests":["EG","EI"],"points":["ATSIX"],"route":["KISWO N864 AVTIC N38 NOKIN P17 POL N601 TLA GOW"]})", true, false},
    AlertCase{"EGVN_C74_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNE"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT"]})", true, false},
    AlertCase{"EGVN_C75_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNT"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL P18 NATEB"]})", true, false},
    AlertCase{"EGVN_C76_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNV"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL P18 GASKO"]})", true, false},
    AlertCase{"EGVN_C77_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGPD"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL P18 ADN"],"restrictions":[{"alt":["N601 GRICE P600 ADN","UN601 TLA DCT GRICE P600 ADN"],"start":{"date":1,"time":"0530"},"end":{"date":1,"time":"0900"}}],"alerts":[{"srd":225,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C78_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGPE"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 TLA GOW INBAS N560 GUSSI INS"],"alerts":[{"srd":416,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false},{"srd":416,"note":"Route will enter Class G airspace if routing below the variable base of N560.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C79_alerts", R"({"dir":"even","min":255,"max":245,"nodests":["EG","EI"],"points":["ATSIX"],"route":["DTY Y53 SAPCO N57 POL N601 TLA GOW STN AKIVO"]})", true, false},
    AlertCase{"EGVN_C80_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNC"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 ABEVI"]})", true, false},
    AlertCase{"EGVN_C81_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNH","EGNL","EGNO"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL"]})", true, false},
    AlertCase{"EGVN_C82_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNM"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 DENBY LBA"]})", true, false},
    AlertCase{"EGVN_C83_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNM"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TIPIL LBA"]})", true, false},
    AlertCase{"EGVN_C84_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGPD"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 GRICE P600 ADN"]})", true, false},
    AlertCase{"EGVN_C85_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGPN"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 TLA EDN"]})", true, false},
    AlertCase{"EGVN_C86_alerts", R"({"dir":"even","min":255,"max":105,"nodests":["EG","EI"],"points":["BAGSO"],"route":["DTY Y53 WAL L10 PENIL L70 BABRA"]})", true, false},
    AlertCase{"EGVN_C87_alerts", R"({"dir":"even","min":255,"max":105,"nodests":["EG","EI"],"points":["BAGSO"],"route":["DTY Y53 WAL L10 PENIL M144 BABRA"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C88_alerts", R"({"dir":"even","min":255,"max":105,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["BAGSO"],"route":["DTY Y53 WAL L10 PENIL M144 BABRA"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}],"alerts":[{"srd":455,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C89_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGCC"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT QUSHI DAYNE"]})", true, false},
    AlertCase{"EGVN_C90_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGGP","EGNR"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT NANTI KEGUN"]})", true, false},
    AlertCase{"EGVN_C91_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGNS"],"nodests":["EG","EI"],"route":["DTY Y53 WAL L10 KELLY"]})", true, false},
    AlertCase{"EGVN_C92_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGNS"],"nodests":["EG","EI"],"route":["DTY Y53 WAL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGVN_C93_alerts", R"({"dir":"even","min":145,"max":175,"nodests":["EG","EI"],"points":["BAGSO"],"route":["KISWO N864 WAL L10 PENIL L70"]})", true, false},
    AlertCase{"EGVN_C94_alerts", R"({"dir":"even","min":145,"max":175,"dests":["EIDW"],"nodests":["EG","EI"],"route":["KISWO N864 WAL L10 PENIL L70 BAGSO"]})", true, false},
    AlertCase{"EGVN_C95_alerts", R"({"dir":"even","min":155,"max":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["KISWO N864 WAL L10 PENIL L28 LELDO M145"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C96_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDG","EIDW","EIME","EIWT"],"nodests":["EG","EI"],"points":["BAGSO"],"route":["KISWO N864 WAL L10 PENIL L28 LELDO M145"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGVN_C97_alerts", R"({"dir":"even","min":155,"max":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["KISWO N864 WAL L10 PENIL M144"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C98_alerts", R"({"dir":"even","min":155,"max":245,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["BAGSO"],"route":["KISWO N864 WAL L10 PENIL M144"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGVN_C99_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EGAA"],"nodests":["EG","EI"],"route":["KISWO N864 WAL M146 IPSET P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C100_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EGNT"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P17 POL"]})", true, false},
    AlertCase{"EGVN_C101_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EGNV"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P17 POL P18 GASKO"]})", true, false},
    AlertCase{"EGVN_C102_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P17 POL N601 RIBEL"]})", true, false},
    AlertCase{"EGVN_C103_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EGPH"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P17 POL N601 INPIP"]})", true, false},
    AlertCase{"EGVN_C104_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["CONKO Q63 OZZIL N80 ARPAK L9 NICXI M17 VATRY"]})", true, false},
    AlertCase{"EGVN_C105_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["CONKO Q63 OZZIL N80 ARPAK L9 NICXI N546 EVTOL N12 NIRIF"],"alerts":[{"srd":113,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C106_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["CONKO Q63 OZZIL N80 ARPAK L9 NICXI N546 EVTOL N12 NIRIF"],"restrictions":[{"start":{"date":0,"time":"1800"},"end":{"date":1,"time":"0900"}}]})", true, false},
    AlertCase{"EGVN_C107_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["CONKO Q63 OZZIL N80 ARPAK L9 NICXI Q63 VATRY"]})", true, false},
    AlertCase{"EGVN_C108_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["KISWO N864 WAL L10 PENIL L28 LELDO M145 BAGSO"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C109_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["KISWO N864 WAL L10 PENIL L28 LELDO M145 BAGSO"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGVN_C110_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["KISWO N864 WAL L10 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C111_alerts", R"({"dir":"even","min":155,"max":245,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["KISWO N864 WAL L10 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGVN_C112_alerts", R"({"dir":"even","min":155,"max":245,"nodests":["EG","EI"],"points":["SLANY"],"route":["CONKO Q63 OZZIL N80 ARPAK L9"]})", true, false},
    AlertCase{"EGVN_C113_alerts", R"({"dir":"even","min":155,"max":245,"nodests":["EG","EI"],"points":["VATRY"],"route":["CONKO Q63 OZZIL N80 ARPAK L9 NICXI M17"]})", true, false},
    AlertCase{"EGVN_C114_alerts", R"({"dir":"even","min":155,"max":245,"nodests":["EG","EI"],"points":["VATRY"],"route":["CONKO Q63 OZZIL N80 ARPAK L9 NICXI Q63"]})", true, false},
    AlertCase{"EGVN_C115_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGAA"],"nodests":["EG","EI"],"route":["DTY Y53 WAL L10 IOM NELBO P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C116_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGAA","EGAE"],"nodests":["EG","EI"],"route":["DTY Y53 WAL M146 IPSET P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C117_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGAC"],"nodests":["EG","EI"],"route":["DTY Y53 WAL L10 IOM NELBO MAGEE"]})", true, false},
    AlertCase{"EGVN_C118_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGAC"],"nodests":["EG","EI"],"route":["DTY Y53 WAL M146 ROBOP M147 MAGEE"]})", true, false},
    AlertCase{"EGVN_C119_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGAE"],"nodests":["EG","EI"],"route":["DTY Y53 WAL L10 BELZU"]})", true, false},
    AlertCase{"EGVN_C120_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGCC","EGGP","EGNR"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT"]})", true, false},
    AlertCase{"EGVN_C121_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EGAA"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 IOM NELBO P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C122_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EGAA","EGAE"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL M146 IPSET P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C123_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EGAC"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 IOM NELBO MAGEE"]})", true, false},
    AlertCase{"EGVN_C124_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EGAC"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL M146 ROBOP M147 MAGEE"]})", true, false},
    AlertCase{"EGVN_C125_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EGAE"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 BELZU"]})", true, false},
    AlertCase{"EGVN_C126_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 PENIL L28 LELDO M145 BAGSO"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C127_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 PENIL L28 LELDO M145 BAGSO"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGVN_C128_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 PENIL L70 BAGSO"]})", true, false},
    AlertCase{"EGVN_C129_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C130_alerts", R"({"dir":"even","min":105,"max":195,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGVN_C131_alerts", R"({"dir":"even","min":155,"max":175,"dests":["EGAA"],"nodests":["EG","EI"],"route":["KISWO N864 WAL L10 IOM NELBO P6 BELZU"]})", true, false},
    AlertCase{"EGVN_C132_alerts", R"({"dir":"even","min":0,"max":75,"dests":["EGBB"],"nodests":["EG","EI"],"route":["DTY L10 HON"]})", true, false},
    AlertCase{"EGVN_C133_alerts", R"({"dir":"odd","min":105,"max":245,"dests":["EGCC","EGGP","EGNR"],"nodests":["EG","EI"],"route":["DTY Y250 AKUPA T420 ELVOS"]})", true, false},
    AlertCase{"EGVN_C134_alerts", R"({"dir":"odd","min":105,"max":245,"dests":["EGCC"],"nodests":["EG","EI"],"route":["DTY Y250 AKUPA T420 TNT QUSHI DAYNE"]})", true, false},
    AlertCase{"EGVN_C135_alerts", R"({"dir":"odd","min":105,"max":245,"dests":["EGGP","EGNR"],"nodests":["EG","EI"],"route":["DTY Y250 AKUPA T420 TNT NANTI KEGUN"]})", true, false},
    AlertCase{"EGVN_C136_alerts", R"({"dir":"odd","min":105,"max":245,"dests":["EGTB"],"nodests":["EG","EI"],"route":["CONKO L18 UNZIB L607 NUCHU CPT"]})", true, false},
    AlertCase{"EGVN_C137_alerts", R"({"dir":"odd","min":105,"max":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["CONKO L18 UNZIB L607 ALHAD N859 VAPID EVTES N621 SAM N63"]})", true, false},
    AlertCase{"EGVN_C138_alerts", R"({"dir":"odd","min":105,"max":245,"nodests":["EG","EI"],"points":["SITET"],"route":["CONKO L18 UNZIB L607 ALHAD N859"]})", true, false},
    AlertCase{"EGVN_C139_alerts", R"({"dir":"even","min":255,"max":175,"dests":["EGCC"],"nodests":["EG","EI"],"route":["KISWO N864 WAL MIRSI"]})", true, false},
    AlertCase{"EGVN_C140_alerts", R"({"dir":"even","min":255,"max":175,"dests":["EGNT"],"nodests":["EG","EI"],"route":["KISWO N864 AVTIC N38 NOKIN P17 POL P18 NATEB"]})", true, false},
    AlertCase{"EGVN_C141_alerts", R"({"dir":"even","min":145,"max":245,"dests":["EGCC"],"nodests":["EG","EI"],"route":["KISWO N864 MONTY"]})", true, false},
    AlertCase{"EGVN_C142_alerts", R"({"dir":"odd","min":245,"max":95,"dests":["EGGW","EGKB","EGLC","EGMC","EGSC","EGSS"],"nodests":["EG","EI"],"route":["CONKO CPT M183 SILVA"]})", true, false},
    AlertCase{"EGVN_C143_alerts", R"({"dir":"odd","min":245,"max":95,"dests":["EGGW"],"nodests":["EG","EI"],"route":["CONKO CPT Q63 ICTAM Q295 MATCH LOFFO"]})", true, false},
    AlertCase{"EGVN_C144_alerts", R"({"dir":"odd","min":245,"max":95,"dests":["EGHH","EGHI"],"nodests":["EG","EI"],"route":["CONKO CPT"]})", true, false},
    AlertCase{"EGVN_C145_alerts", R"({"dir":"odd","min":245,"max":95,"dests":["EGKK"],"nodests":["EG","EI"],"route":["CONKO CPT N859 GWC"]})", true, false},
    AlertCase{"EGVN_C146_alerts", R"({"dir":"odd","min":245,"max":95,"dests":["EGKK","EGLL","EGWU"],"nodests":["EG","EI"],"route":["CONKO KENET NIGIT"]})", true, false},
    AlertCase{"EGVN_C147_alerts", R"({"dir":"odd","min":245,"max":95,"dests":["EGLL","EGWU"],"nodests":["EG","EI"],"route":["CONKO KENET NIGIT OCK"]})", true, false},
    AlertCase{"EGVN_C148_alerts", R"({"dir":"odd","min":65,"max":75,"dests":["EGLF","EGLK"],"nodests":["EG","EI"],"route":["CONKO CPT"]})", true, false},
    AlertCase{"EGVN_C149_alerts", R"({"dir":"odd","min":65,"max":75,"dests":["EGTO"],"nodests":["EG","EI"],"route":["CONKO CPT N859 GWC SFD Y803 LYD DET"]})", true, false},
    AlertCase{"EGVN_C150_alerts", R"({"dir":"even","min":95,"max":245,"dests":["EGNJ"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT M868 ADELU UPTON L975 GOLES"]})", true, false},
    AlertCase{"EGVN_C151_alerts", R"({"dir":"even","min":95,"max":245,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 RIBEL"]})", true, false},
    AlertCase{"EGVN_C152_alerts", R"({"dir":"even","min":95,"max":245,"dests":["EGPH"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 INPIP"]})", true, false},
    AlertCase{"EGVN_C153_alerts", R"({"dir":"even","min":95,"max":245,"dests":["EGPT"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL N601 GRICE P600 PTH"]})", true, false},
    AlertCase{"EGVN_C154_alerts", R"({"dir":"even","min":255,"max":95,"dests":["EGNJ"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 DENBY L975 GOLES"]})", true, false},
    AlertCase{"EGVN_C155_alerts", R"({"dir":"even","min":105,"max":185,"dests":["EGNS"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL L10 KELLY"]})", true, false},
    AlertCase{"EGVN_C156_alerts", R"({"dir":"even","min":105,"max":185,"dests":["EGNS"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT Q4 WAL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGVN_C157_alerts", R"({"dir":"even","min":185,"max":245,"dests":["EGNS"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 AGLIL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGVN_C158_alerts", R"({"dir":"even","min":185,"max":245,"dests":["EGNS"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 TNT L28 PENIL L10 KELLY"]})", true, false},
    AlertCase{"EGVN_C159_alerts", R"({"dir":"odd","min":245,"max":345,"dests":["EGNT"],"nodests":["EG","EI"],"route":["KISWO AVTIC ANJAK N38 NOKIN UP17 POL"]})", true, false},
    AlertCase{"EGVN_C160_alerts", R"({"dir":"odd","min":245,"max":345,"dests":["EGNV"],"nodests":["EG","EI"],"route":["KISWO AVTIC ANJAK N38 NOKIN UP17 POL P18 GASKO"]})", true, false},
    AlertCase{"EGVN_C161_alerts", R"({"dir":"even","min":75,"max":195,"dests":["EGNT"],"nodests":["EG","EI"],"route":["DTY Y53 SAPCO N57 POL"]})", true, false},
    AlertCase{"EGVN_C162_alerts", R"({"dir":"odd","min":245,"max":245,"dests":["EGNX"],"nodests":["EG","EI"],"route":["DTY"]})", true, false},
    AlertCase{"EGVN_C163_alerts", R"({"dir":"odd","min":245,"max":245,"nodests":["EG","EI"],"points":["NAVPI"],"route":["BZN MAM"],"alerts":[{"srd":84,"note":"Approved vSOA operations only.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C164_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["DTY UY53 SAPCO UN57 POL UN601 RIBEL"]})", true, false},
    AlertCase{"EGVN_C165_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPH"],"nodests":["EG","EI"],"route":["DTY UY53 SAPCO UN57 POL UN601 INPIP"]})", true, false},
    AlertCase{"EGVN_C166_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPN"],"nodests":["EG","EI"],"route":["DTY UY53 SAPCO UN57 POL UN601 TLA EDN"]})", true, false},
    AlertCase{"EGVN_C167_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPT"],"nodests":["EG","EI"],"route":["DTY UY53 SAPCO UN57 POL UN601 TLA N601 GRICE P600 PTH"]})", true, false},
    AlertCase{"EGVN_C168_alerts", R"({"dir":"odd","min":245,"max":255,"dests":["EGPK"],"nodests":["EG","EI"],"route":["KISWO AVTIC ANJAK N38 NOKIN UP16 RIBEL"]})", true, false},
    AlertCase{"EGVN_C169_alerts", R"({"dir":"odd","min":245,"dests":["EGPK"],"nodests":["EG","EI"],"route":["KISWO AVTIC ANJAK N38 NOKIN UP16 RIBEL"]})", true, false},
    AlertCase{"EGVN_C170_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["KONAN"],"route":["CONKO L18 UNZIB L607"]})", true, false},
    AlertCase{"EGVN_C171_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["CONKO L18 UNZIB L607 ALHAD UN859 VAPID EVTES N621 SAM M195 MARUK N621"]})", true, false},
    AlertCase{"EGVN_C172_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"route":["CONKO L18 UNZIB L607 ALHAD UN859 VAPID EVTES N621 SAM N866"],"alerts":[{"srd":271,"note":"reroute via LELNA","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C173_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"nopoints":["ARE","DIN"],"route":["CONKO L18 UNZIB L607 ALHAD UN859 VAPID EVTES N621 SAM N866"],"restrictions":[{"alt":["reroute via LELNA"]}],"alerts":[{"srd":271,"note":"If after leaving the UK the aircraft routes via ARE or DIN, it must re-file using a route that exits UK at LELNA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C174_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["NAVPI"],"route":["BZN TR1"],"alerts":[{"srd":84,"note":"Approved vSOA operations only.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C175_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["REDFA"],"route":["CONKO L18 UNZIB L607 ALHAD P72 IPRIL M197"]})", true, false},
    AlertCase{"EGVN_C176_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["SITET"],"route":["CONKO L18 UNZIB L607 ALHAD UN859"]})", true, false},
    AlertCase{"EGVN_C177_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["SOMVA"],"route":["CONKO L18 UNZIB L607 ALHAD P72 IPRIL M197 BRAIN Q295"]})", true, false},
    AlertCase{"EGVN_C178_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["XAMAB"],"route":["CONKO L18 UNZIB L607 ALHAD UN859 VAPID L18 MID UL612"]})", true, false},
    AlertCase{"EGVN_C179_alerts", R"({"dir":"odd","min":245,"max":105,"dests":["EGTB"],"nodests":["EG","EI"],"route":["CONKO CPT"]})", true, false},
    AlertCase{"EGVN_C180_alerts", R"({"dir":"odd","min":245,"max":105,"nodests":["EG","EI"],"points":["ORTAC"],"route":["CONKO CPT Y321 PEPIS Q41"]})", true, false},
    AlertCase{"EGVN_C181_alerts", R"({"dir":"even","min":145,"max":105,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 WAL L10 PENIL L70 BAGSO"]})", true, false},
    AlertCase{"EGVN_C182_alerts", R"({"dir":"even","min":155,"max":105,"dests":["EIDW"],"nodests":["EG","EI"],"route":["DTY Y53 WAL L10 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGVN_C183_alerts", R"({"dir":"even","min":155,"max":105,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["DTY Y53 WAL L10 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}],"alerts":[{"srd":455,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGVN_C184_alerts", R"({"dir":"odd","min":255,"nodests":["EG","EI"],"points":["INBOB","PENUN","SOPTO"],"route":["CONKO L18 UNZIB L607 ALHAD P72 IPRIL M197 BRAIN Q295 PAAVO M604 LARGA"]})", true, false},
    AlertCase{"EGVN_C185_alerts", R"({"dir":"odd","min":105,"max":175,"nodests":["EG","EI"],"points":["KONAN"],"route":["CONKO L18 UNZIB L607 NUCHU CPT L9"]})", true, false},
    AlertCase{"EGVN_C186_alerts", R"({"dir":"odd","min":105,"max":175,"nodests":["EG","EI"],"points":["VABIK"],"route":["CONKO L18 UNZIB L607 NUCHU CPT L9 BIG Q70"]})", true, false},
    AlertCase{"EGVN_C187_alerts", R"({"dir":"odd","min":175,"max":245,"nodests":["EG","EI"],"points":["KONAN"],"route":["CONKO L18 UNZIB L607 BIG L9"]})", true, false},
    AlertCase{"EGVN_C188_alerts", R"({"dir":"odd","min":195,"max":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["CONKO L18 UNZIB L607 ALHAD N859 VAPID EVTES N621 SAM M195 MARUK N621"]})", true, false},
    AlertCase{"EGVN_C189_alerts", R"({"dir":"odd","min":165,"max":245,"nodests":["EG","EI"],"points":["NAVPI"],"route":["CONKO L18 UNZIB L607 ALHAD P72 BPK UMBAG","CONKO L18 UNZIB L607 ALHAD P72 BPK N16 BKY"]})", true, false},
    AlertCase{"EGVN_C190_alerts", R"({"dir":"odd","min":165,"max":245,"nodests":["EG","EI"],"points":["REDFA"],"route":["CONKO L18 UNZIB L607 ALHAD P72 IPRIL M197"]})", true, false},
    AlertCase{"EGVN_C191_alerts", R"({"dir":"odd","min":165,"max":245,"nodests":["EG","EI"],"points":["XIDIL"],"route":["CONKO L18 UNZIB L607 ALHAD N859 VAPID L18 MID Y803 SFD M605"]})", true, false},
    AlertCase{"EGVN_C192_alerts", R"({"dir":"odd","min":245,"max":165,"nodests":["EG","EI"],"points":["NAVPI"],"route":["CONKO L18 UNZIB L607 NUCHU CPT Q63 ICTAM Q295 BPK UMBAG","CONKO L18 UNZIB L607 NUCHU CPT Q63 ICTAM Q295 BPK N16 BKY"]})", true, false},
    AlertCase{"EGVN_C193_alerts", R"({"dir":"odd","min":245,"max":165,"nodests":["EG","EI"],"points":["XAMAB"],"route":["CONKO L18 UNZIB L607 ALHAD N859 GWC BOGNA"]})", true, false},
    AlertCase{"EGVN_C194_alerts", R"({"dir":"odd","min":105,"max":165,"nodests":["EG","EI"],"points":["REDFA"],"route":["CONKO L18 UNZIB L607 NUCHU CPT Q63 ICTAM M197"]})", true, false},
    AlertCase{"EGVN_C195_alerts", R"({"dir":"odd","min":105,"max":165,"nodests":["EG","EI"],"points":["REDFA"],"route":["CONKO L18 UNZIB L607 NUCHU CPT Q63 ICTAM M197 BRAIN P44 CLN L620"]})", true, false},
    AlertCase{"EGVN_C196_alerts", R"({"dir":"odd","min":165,"max":175,"nodests":["EG","EI"],"points":["REDFA"],"route":["CONKO L18 UNZIB L607 ALHAD P72 IPRIL M197 BRAIN P44 CLN L620"]})", true, false},
    AlertCase{"EGVN_C197_alerts", R"({"dir":"odd","min":175,"max":295,"nodests":["EG","EI"],"points":["VABIK"],"route":["CONKO L18 UNZIB L607 BIG Q70"]})", true, false},
    AlertCase{"EGVN_C198_alerts", R"({"dir":"odd","min":165,"max":205,"nodests":["EG","EI"],"points":["XAMAB"],"route":["CONKO L18 UNZIB L607 ALHAD N859 VAPID L18 MID L612 BOGNA"]})", true, false},
    AlertCase{"EGVN_C199_alerts", R"({"dir":"odd","min":215,"max":245,"nodests":["EG","EI"],"points":["XAMAB"],"route":["CONKO L18 UNZIB L607 ALHAD MID L612"]})", true, false},
    AlertCase{"EGVN_C200_alerts", R"({"dir":"odd","min":215,"max":245,"nodests":["EG","EI"],"points":["XIDIL"],"route":["CONKO L18 UNZIB L607 ALHAD MID Y803 SFD M605"]})", true, false},
    AlertCase{"EGVN_C201_alerts", R"({"dir":"odd","min":245,"max":295,"nodests":["EG","EI"],"points":["XIDIL"],"route":["CONKO L18 UNZIB L607 ALHAD MID Y803 SFD UM605"]})", true, false},
    AlertCase{"EGVN_C202_alerts", R"({"dir":"odd","min":105,"max":155,"nodests":["EG","EI"],"points":["XIDIL"],"route":["CONKO L18 UNZIB L607 ALHAD N859 GWC Y8 WAFFU M605"]})", true, false},
    AlertCase{"EGWU_C0_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["ADARA","DINIM","LIMRI","TOBOR"],"route":["L9 BUCGO FELCA OFSOX BANBA"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C1_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["AGORI","BILTO","SUNOT"],"route":["L9 DIDZA N14 OKTAD MEDOG LANON LIPGO REVNU","L9 DIDZA N14 OKTAD MEDOG VATRY REVNU"]})", true, false},
    AlertCase{"EGWU_C2_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["ARKIL","GAPLI","LULOX"],"route":["Y321 EXARO N514 ADKIK JOZMA"]})", true, false},
    AlertCase{"EGWU_C3_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BAKUR"],"route":["L9 BUCGO FELCA NICXI"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C4_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BANBA","ENJEX","SLANY"],"route":["L9 BUCGO FELCA OFSOX"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C5_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BILTO"],"route":["L9 BUCGO FELCA NICXI BAKUR REVNU"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C6_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["DOGAL","ETARI","PIKIL","RESNO","VENER","MOLAK","NEBIN"],"route":["L9 BUCGO FELCA NICXI BAKUR"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C7_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["DOGAL","NEBIN","MALOT"],"route":["L9 BUCGO FELCA OFSOX SLANY"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C8_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["DOGAL"],"route":["L9 DIDZA N14 OKTAD MEDOG KRAGY PEMOB VATRY"]})", true, false},
    AlertCase{"EGWU_C9_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG FOXLA NICXI LANPI Q63 VATRY"]})", true, false},
    AlertCase{"EGWU_C10_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG FOXLA NICXI PEMOB M17 VATRY"]})", true, false},
    AlertCase{"EGWU_C11_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG KRAGY PEMOB LANPI Q63 VATRY"]})", true, false},
    AlertCase{"EGWU_C12_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG KRAGY PEMOB M17 VATRY","L9 DIDZA N14 OKTAD MEDOG LANON L18 ABLIN"]})", true, false},
    AlertCase{"EGWU_C13_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG PEMOB EVTOL N12 NIRIF"],"restrictions":[{"start":{"date":0,"time":"2359"},"end":{"date":1,"time":"0759"}}]})", true, false},
    AlertCase{"EGWU_C14_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["ETARI","PIKIL","RESNO","MOLAK"],"route":["L9 DIDZA N14 OKTAD MEDOG VATRY"]})", true, false},
    AlertCase{"EGWU_C15_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["LEDGO"],"route":["Y321 EXARO N514 ADKIK FONZU"],"alerts":[{"srd":518,"note":"Flight must not terminate in EI/Ireland.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C16_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["LESLU"],"route":["Y321 EXARO N514 ADKIK FONZU"]})", true, false},
    AlertCase{"EGWU_C17_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["LIPGO"],"route":["L9 DIDZA N14 OKTAD MEDOG LANON"]})", true, false},
    AlertCase{"EGWU_C18_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["MOPAT"],"route":["Y321 EXARO N514 ADKIK","Y321 EXARO N514 ADKIK PEWBI"]})", true, false},
    AlertCase{"EGWU_C19_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["RESNO","VENER"],"route":["L9 DIDZA N14 OKTAD MEDOG LANON LIPGO"]})", true, false},
    AlertCase{"EGWU_C20_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["VATRY"],"route":["L9 DIDZA N14 OKTAD MEDOG","L9 DIDZA N14 OKTAD MEDOG KRAGY PEMOB"]})", true, false},
    AlertCase{"EGWU_C21_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["VATRY"],"route":["L9 DIDZA N14 OKTAD MEDOG FOXLA NICXI"]})", true, false},
    AlertCase{"EGWU_C22_alerts", R"({"dir":"even","min":305,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG FOXLA NICXI EVTOL N12 NIRIF"]})", true, false},
    AlertCase{"EGWU_C23_alerts", R"({"dir":"even","min":245,"max":305,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 DIDZA N14 OKTAD MEDOG FOXLA NICXI EVTOL N12 NIRIF"],"restrictions":[{"start":{"date":0,"time":"1800"},"end":{"date":1,"time":"0900"}}]})", true, false},
    AlertCase{"EGWU_C24_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["AGORI"],"route":["L9 DIDZA N14 OKTAD MEDOG LANON LIPGO ERNAN MIMKU","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN MIMKU"]})", true, false},
    AlertCase{"EGWU_C25_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["BILTO"],"route":["L9 BUCGO FELCA NICXI BAKUR ERNAN MIMKU","L9 BUCGO FELCA NICXI BAKUR ERNAN NIBOG"],"alerts":[{"srd":504,"note":"L9 BIBPE DCT BUCGO DCT FELCA may be filed for these entries as an alternative to L9 BUCGO DCT FELCA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C26_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["BILTO"],"route":["L9 DIDZA N14 OKTAD MEDOG LANON LIPGO ERNAN MIMKU","L9 DIDZA N14 OKTAD MEDOG LANON LIPGO ERNAN NIBOG","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN MIMKU","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN NIBOG"]})", true, false},
    AlertCase{"EGWU_C27_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN NIBOG"]})", true, false},
    AlertCase{"EGWU_C28_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["SUNOT"],"route":["L9 DIDZA N14 OKTAD MEDOG LANON LIPGO ERNAN AMLAD","L9 DIDZA N14 OKTAD MEDOG LANON LIPGO ERNAN MIMKU","L9 DIDZA N14 OKTAD MEDOG LANON LIPGO ERNAN NIBOG","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN AMLAD","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN APSOV","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN MIMKU","L9 DIDZA N14 OKTAD MEDOG VATRY ERNAN NIBOG"]})", true, false},
    AlertCase{"EGWU_C29_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["AMPOP","TALIG"],"route":["Y321 EXARO N514 ADKIK JOZMA"]})", true, false},
    AlertCase{"EGWU_C30_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"route":["Y321 PEPIS Q41 SAM M195"]})", true, false},
    AlertCase{"EGWU_C31_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"route":["Y321 PEPIS Q41 SAM N621 MARUK M195"],"alerts":[{"srd":271,"note":"reroute via LELNA","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C32_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"nopoints":["ARE","DIN"],"route":["Y321 PEPIS Q41 SAM N621 MARUK M195"],"restrictions":[{"alt":["reroute via LELNA"]}],"alerts":[{"srd":271,"note":"If after leaving the UK the aircraft routes via ARE or DIN, it must re-file using a route that exits UK at LELNA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C33_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["SITET"],"route":["N859 DRAKE L151"]})", true, false},
    AlertCase{"EGWU_C34_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["XAMAB"],"route":["MID UL612"]})", true, false},
    AlertCase{"EGWU_C35_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EGBJ"],"nodests":["EG","EI"],"route":["Q63 ASHUM"]})", true, false},
    AlertCase{"EGWU_C36_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EGTE"],"nodests":["EG","EI"],"route":["Y321 PEPIS Q41 SAM L620 GIBSO"]})", true, false},
    AlertCase{"EGWU_C37_alerts", R"({"dir":"even","min":65,"max":245,"dests":["EGFF","EGGD"],"nodests":["EG","EI"],"route":["Q63 SAWPE"]})", true, false},
    AlertCase{"EGWU_C38_alerts", R"({"dir":"even","min":65,"max":75,"dests":["EGHH","EGHI"],"nodests":["EG","EI"]})", true, false},
    AlertCase{"EGWU_C39_alerts", R"({"dir":"even","min":65,"max":75,"dests":["EGTK"],"nodests":["EG","EI"],"route":["KENET BUGUP"]})", true, false},
    AlertCase{"EGWU_C40_alerts", R"({"dir":"even","min":65,"max":75,"dests":["EGVN"],"nodests":["EG","EI"],"route":["Q63 ASHUM NAXAT"]})", true, false},
    AlertCase{"EGWU_C41_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EGHQ"],"nodests":["EG","EI"],"route":["Y321 PEPIS Q41 SAM L620 DAWLY"]})", true, false},
    AlertCase{"EGWU_C42_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 NICXI M17 VATRY"]})", true, false},
    AlertCase{"EGWU_C43_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 NICXI N546 EVTOL N12 NIRIF"],"alerts":[{"srd":113,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C44_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 NICXI N546 EVTOL N12 NIRIF"],"restrictions":[{"start":{"date":0,"time":"1800"},"end":{"date":1,"time":"0900"}}]})", true, false},
    AlertCase{"EGWU_C45_alerts", R"({"dir":"even","min":195,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["L9 NICXI Q63 VATRY"]})", true, false},
    AlertCase{"EGWU_C46_alerts", R"({"dir":"even","min":195,"max":245,"nodests":["EG","EI"],"points":["ENJEX"],"route":["L9 OFSOX N83"]})", true, false},
    AlertCase{"EGWU_C47_alerts", R"({"dir":"even","min":195,"max":245,"nodests":["EG","EI"],"points":["VATRY"],"route":["L9 NICXI M17"]})", true, false},
    AlertCase{"EGWU_C48_alerts", R"({"dir":"even","min":245,"max":195,"dests":["EGHQ"],"nodests":["EG","EI"],"route":["Y321 PEPIS Q41 SAM GIBSO DAWLY"]})", true, false},
    AlertCase{"EGWU_C49_alerts", R"({"dir":"odd","min":65,"max":75,"dests":["EGLF","EGLK"],"nodests":["EG","EI"]})", true, false},
    AlertCase{"EGWU_C50_alerts", R"({"dir":"odd","min":35,"max":45,"dests":["EGLL"],"nodests":["EG","EI"],"route":["BNN"]})", true, false},
    AlertCase{"EGWU_C51_alerts", R"({"dir":"even","min":155,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["Q63 OZZIL N80 ARPAK L9 NICXI M17 VATRY","Q63 OZZIL N80 ARPAK L9 NICXI Q63 VATRY"]})", true, false},
    AlertCase{"EGWU_C52_alerts", R"({"dir":"even","min":155,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["Q63 OZZIL N80 ARPAK L9 NICXI N546 EVTOL N12 NIRIF"],"alerts":[{"srd":113,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C53_alerts", R"({"dir":"even","min":155,"max":195,"dests":["EIDW"],"nodests":["EG","EI"],"route":["Q63 OZZIL N80 ARPAK L9 NICXI N546 EVTOL N12 NIRIF"],"restrictions":[{"start":{"date":0,"time":"1800"},"end":{"date":1,"time":"0900"}}]})", true, false},
    AlertCase{"EGWU_C54_alerts", R"({"dir":"even","min":155,"max":195,"nodests":["EG","EI"],"points":["ENJEX"],"route":["Q63 OZZIL N80 ARPAK L9 OFSOX N83"]})", true, false},
    AlertCase{"EGWU_C55_alerts", R"({"dir":"even","min":155,"max":195,"nodests":["EG","EI"],"points":["VATRY"],"route":["Q63 OZZIL N80 ARPAK L9 NICXI M17"]})", true, false},
    AlertCase{"EGWU_C56_alerts", R"({"dir":"odd","min":105,"max":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["Y321 PEPIS Q41 SAM N63"]})", true, false},
    AlertCase{"EGWU_C57_alerts", R"({"dir":"odd","min":195,"nodests":["EG","EI"],"points":["LELNA"],"route":["Y321 PEPIS Q41 SAM M195 MARUK N621"]})", true, false},
    AlertCase{"EGWU_C58_alerts", R"({"dir":"odd","min":195,"nodests":["EG","EI"],"points":["LELNA"],"route":["Y321 PEPIS Q41 SAM N621"],"alerts":[{"srd":272,"note":"reroute via LORKU","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C59_alerts", R"({"dir":"odd","min":195,"nodests":["EG","EI"],"points":["LELNA"],"nopoints":["QPR"],"route":["Y321 PEPIS Q41 SAM N621"],"restrictions":[{"alt":["reroute via LORKU"]}],"alerts":[{"srd":272,"note":"If after leaving the UK the aircraft routes via QPR, it must re-file using a route that exits UK at LORKU.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C60_alerts", R"({"dir":"odd","min":245,"max":205,"nodests":["EG","EI"],"points":["NEVIL"],"route":["N859 DRAKE OSPOL M189"]})", true, false},
    AlertCase{"EGWU_C61_alerts", R"({"dir":"odd","min":85,"max":105,"nodests":["EG","EI"],"points":["ORTAC"],"route":["Y321 PEPIS Q41"]})", true, false},
    AlertCase{"EGWU_C62_alerts", R"({"dir":"odd","min":85,"max":245,"nodests":["EG","EI"],"points":["SITET"],"route":["N859","N859 DRAKE L151"]})", true, false},
    AlertCase{"EGWU_C63_alerts", R"({"dir":"odd","min":85,"max":245,"nodests":["EG","EI"],"points":["XIDIL"],"route":["MID Y803 SFD M605"]})", true, false},
    AlertCase{"EGWU_C64_alerts", R"({"dir":"even","min":195,"max":195,"nodests":["EG","EI"],"points":["SLANY"],"route":["L9"]})", true, false},
    AlertCase{"EGWU_C65_alerts", R"({"dir":"odd","min":245,"max":245,"nodests":["EG","EI"],"points":["XAMAB"],"route":["MID L612"]})", true, false},
    AlertCase{"EGWU_C66_alerts", R"({"dir":"odd","min":245,"max":295,"nodests":["EG","EI"],"points":["XIDIL"],"route":["MID"]})", true, false},
    AlertCase{"EGWU_C67_alerts", R"({"dir":"even","min":245,"dests":["EGPH"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 INPIP"]})", true, false},
    AlertCase{"EGWU_C68_alerts", R"({"dir":"even","min":245,"dests":["EGPN"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 TLA EDN"]})", true, false},
    AlertCase{"EGWU_C69_alerts", R"({"dir":"even","min":245,"dests":["EGPT"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 TLA N601 GRICE P600 PTH"]})", true, false},
    AlertCase{"EGWU_C70_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["T420 TNT UL28 LELDO M145 BAGSO"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C71_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["T420 TNT UL28 LELDO M145 BAGSO"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGWU_C72_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["T420 TNT UL28 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C73_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["T420 TNT UL28 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGWU_C74_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["T420 TNT UL28 PENIL UL70 BAGSO"]})", true, false},
    AlertCase{"EGWU_C75_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["RESNO"],"route":["T420 TNT UL28 RODOL UM65 TENSO L603 BELOX NIBOG"]})", true, false},
    AlertCase{"EGWU_C76_alerts", R"({"dir":"even","min":255,"max":105,"nodests":["EG","EI"],"points":["BAGSO"],"route":["WELIN N57 SAPCO Y53 WAL L10 PENIL L70 BABRA"]})", true, false},
    AlertCase{"EGWU_C77_alerts", R"({"dir":"even","min":255,"max":105,"nodests":["EG","EI"],"points":["BAGSO"],"route":["WELIN N57 SAPCO Y53 WAL L10 PENIL M144 BABRA"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C78_alerts", R"({"dir":"even","min":255,"max":105,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["BAGSO"],"route":["WELIN N57 SAPCO Y53 WAL L10 PENIL M144 BABRA"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}],"alerts":[{"srd":455,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C79_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGCN"],"nodests":["EG","EI"],"route":["WELIN N57 TIPIL M868 ADELU L60 MAMUL"]})", true, false},
    AlertCase{"EGWU_C80_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGNS"],"nodests":["EG","EI"],"route":["WELIN N57 SAPCO Y53 WAL L10 KELLY"]})", true, false},
    AlertCase{"EGWU_C81_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EGNS"],"nodests":["EG","EI"],"route":["WELIN N57 SAPCO Y53 WAL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGWU_C82_alerts", R"({"dir":"even","min":255,"max":105,"dests":["EIDW"],"nodests":["EG","EI"],"route":["WELIN N57 SAPCO Y53 WAL L10 PENIL L70 BABRA BAGSO"]})", true, false},
    AlertCase{"EGWU_C83_alerts", R"({"dir":"odd","min":255,"nodests":["EG","EI"],"points":["BEREP","KLONN","RIGVU"],"route":["T420 TNT UN57 POL UN601 TLA"]})", true, false},
    AlertCase{"EGWU_C84_alerts", R"({"dir":"even","min":195,"max":255,"dests":["EGAC"],"nodests":["EG","EI"],"route":["T420 TNT L28 AGLIL M146 ERDUV Z198 MASOP M148 MAGEE"]})", true, false},
    AlertCase{"EGWU_C85_alerts", R"({"dir":"even","min":245,"max":195,"dests":["EGBB","EGBE","EGBG"],"nodests":["EG","EI"]})", true, false},
    AlertCase{"EGWU_C86_alerts", R"({"dir":"even","min":115,"max":195,"dests":["EGCC","EGGP","EGNR"],"nodests":["EG","EI"],"route":["T420 ELVOS"],"alerts":[{"srd":69,"note":"Max flight level of 195 due to city pair capping.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C87_alerts", R"({"dir":"even","min":115,"max":195,"dests":["EGNT"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL"]})", true, false},
    AlertCase{"EGWU_C88_alerts", R"({"dir":"even","min":115,"max":195,"dests":["EGNX"],"nodests":["EG","EI"],"route":["T420 WELIN"]})", true, false},
    AlertCase{"EGWU_C89_alerts", R"({"dir":"even","min":115,"max":195,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 RIBEL"]})", true, false},
    AlertCase{"EGWU_C90_alerts", R"({"dir":"even","min":115,"max":195,"dests":["EGPH"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 INPIP"]})", true, false},
    AlertCase{"EGWU_C91_alerts", R"({"dir":"even","min":115,"max":195,"dests":["EGPT"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 GRICE P600 PTH"]})", true, false},
    AlertCase{"EGWU_C92_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGCC","EGGP"],"nodests":["EG","EI"],"route":["T420 ELVOS TNT"],"alerts":[{"srd":69,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false},{"srd":69,"note":"Max flight level of 195 due to city pair capping.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C93_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGCC"],"nodests":["EG","EI"],"route":["T420 TNT QUSHI DAYNE"]})", true, false},
    AlertCase{"EGWU_C94_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGGP"],"nodests":["EG","EI"],"route":["T420 TNT NANTI KEGUN"],"alerts":[{"srd":69,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false},{"srd":69,"note":"Max flight level of 195 due to city pair capping.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C95_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNH","EGNO"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL"],"alerts":[{"srd":69,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false},{"srd":69,"note":"Max flight level of 195 due to city pair capping.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C96_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNM"],"nodests":["EG","EI"],"route":["T420 TNT N57 DENBY LBA"],"alerts":[{"srd":69,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false},{"srd":69,"note":"Max flight level of 195 due to city pair capping.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C97_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNM"],"nodests":["EG","EI"],"route":["T420 TNT N57 TIPIL LBA"]})", true, false},
    AlertCase{"EGWU_C98_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNR"],"nodests":["EG","EI"],"route":["T420 TNT NANTI KEGUN"]})", true, false},
    AlertCase{"EGWU_C99_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNT"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL P18 NATEB"]})", true, false},
    AlertCase{"EGWU_C100_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNV"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL P18 GASKO"]})", true, false},
    AlertCase{"EGWU_C101_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGPD"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 GRICE P600 ADN"]})", true, false},
    AlertCase{"EGWU_C102_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGPD"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL P18 ADN"],"restrictions":[{"alt":["N601 GRICE P600 ADN","UN601 TLA DCT GRICE P600 ADN"],"start":{"date":1,"time":"0530"},"end":{"date":1,"time":"0900"}}],"alerts":[{"srd":225,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C103_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGPE"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 TLA GOW INBAS N560 GUSSI INS"],"alerts":[{"srd":416,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false},{"srd":416,"note":"Route will enter Class G airspace if routing below the variable base of N560.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C104_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGPN"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 TLA EDN"]})", true, false},
    AlertCase{"EGWU_C105_alerts", R"({"dir":"even","min":75,"max":105,"dests":["EGCN"],"nodests":["EG","EI"],"route":["WELIN N57 TNT"]})", true, false},
    AlertCase{"EGWU_C106_alerts", R"({"dir":"odd","min":35,"max":45,"dests":["EGLL"],"nodests":["EG","EI"],"route":["BNN"]})", true, false},
    AlertCase{"EGWU_C107_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNC"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 ABEVI"]})", true, false},
    AlertCase{"EGWU_C108_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNE"],"nodests":["EG","EI"],"route":["T420 TNT"]})", true, false},
    AlertCase{"EGWU_C109_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNL"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL"]})", true, false},
    AlertCase{"EGWU_C110_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGPD"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 GRICE P600 ADN"]})", true, false},
    AlertCase{"EGWU_C111_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGPN"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 TLA EDN"]})", true, false},
    AlertCase{"EGWU_C112_alerts", R"({"dir":"odd","min":95,"max":195,"dests":["EGNJ"],"nodests":["EG","EI"],"route":["T420 TNT M868 ADELU UPTON L975 GOLES"],"alerts":[{"srd":69,"note":"Max flight level of 195 due to city pair capping.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGWU_C113_alerts", R"({"dir":"even","min":255,"max":95,"dests":["EGNJ"],"nodests":["EG","EI"],"route":["T420 TNT N57 DENBY L975 GOLES"]})", true, false},
    AlertCase{"EGWU_C114_alerts", R"({"dir":"even","min":105,"max":185,"dests":["EGNS"],"nodests":["EG","EI"],"route":["T420 TNT Q4 WAL L10 KELLY"]})", true, false},
    AlertCase{"EGWU_C115_alerts", R"({"dir":"even","min":105,"max":185,"dests":["EGNS"],"nodests":["EG","EI"],"route":["T420 TNT Q4 WAL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGWU_C116_alerts", R"({"dir":"even","min":185,"max":195,"dests":["EGNS"],"nodests":["EG","EI"],"route":["T420 TNT L28 AGLIL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGWU_C117_alerts", R"({"dir":"even","min":185,"max":245,"dests":["EGNS"],"nodests":["EG","EI"],"route":["T420 TNT L28 AGLIL M146 LUSOD IOM"]})", true, false},
    AlertCase{"EGWU_C118_alerts", R"({"dir":"even","min":185,"max":245,"dests":["EGNS"],"nodests":["EG","EI"],"route":["T420 TNT L28 PENIL L10 KELLY"]})", true, false},
    AlertCase{"EGWU_C119_alerts", R"({"dir":"even","min":245,"max":345,"dests":["EGNT"],"nodests":["EG","EI"],"route":["T420 AKUPA UY250 GASKO P18 NATEB"]})", true, false},
    AlertCase{"EGWU_C120_alerts", R"({"dir":"even","min":245,"max":345,"dests":["EGNT"],"nodests":["EG","EI"],"route":["T420 AKUPA UY250 RIMTO"]})", true, false},
    AlertCase{"EGWU_C121_alerts", R"({"dir":"even","min":245,"max":345,"dests":["EGNV"],"nodests":["EG","EI"],"route":["T420 AKUPA UY250 GASKO"]})", true, false},
    AlertCase{"EGWU_C122_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 RIBEL"]})", true, false},
    AlertCase{"EGWU_C123_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPH"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 INPIP"]})", true, false},
    AlertCase{"EGWU_C124_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPN"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 TLA EDN"]})", true, false},
    AlertCase{"EGWU_C125_alerts", R"({"dir":"even","min":245,"max":255,"dests":["EGPT"],"nodests":["EG","EI"],"route":["T420 TNT UN57 POL UN601 TLA N601 GRICE P600 PTH"]})", true, false},
    AlertCase{"EGWU_C126_alerts", R"({"dir":"even","min":115,"max":245,"dests":["EGPF","EGPK"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 RIBEL"]})", true, false},
    AlertCase{"EGWU_C127_alerts", R"({"dir":"even","min":115,"max":245,"dests":["EGPH"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 INPIP"]})", true, false},
    AlertCase{"EGWU_C128_alerts", R"({"dir":"even","min":115,"max":245,"dests":["EGPT"],"nodests":["EG","EI"],"route":["T420 TNT N57 POL N601 GRICE P600 PTH"]})", true, false},
    AlertCase{"EGWU_C129_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["T420 TNT UL28 PENIL M144 BAGSO REVNU"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C130_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["ETARI","PIKIL"],"route":["T420 TNT UL28 PENIL M144 BAGSO REVNU"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGWU_C131_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["T420 TNT UL28 PENIL UL70 BAGSO REVNU"]})", true, false},
    AlertCase{"EGWU_C132_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["RESNO"],"route":["T420 TNT UL28 PENIL M144 BAGSO","T420 TNT UL28 PENIL M144 BAGSO REVNU"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C133_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["RESNO"],"route":["T420 TNT UL28 PENIL M144 BAGSO","T420 TNT UL28 PENIL M144 BAGSO REVNU"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGWU_C134_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["RESNO"],"route":["T420 TNT UL28 PENIL UL70 BAGSO","T420 TNT UL28 PENIL UL70 BAGSO REVNU"]})", true, false},
    AlertCase{"EGWU_C135_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["VENER"],"route":["T420 TNT UL28 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C136_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["VENER"],"route":["T420 TNT UL28 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGWU_C137_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["VENER"],"route":["T420 TNT UL28 PENIL UL70 BAGSO"]})", true, false},
    AlertCase{"EGWU_C138_alerts", R"({"dir":"even","min":255,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["T420 TNT UL28 PENIL M144 BAGSO ERNAN NIBOG"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGWU_C139_alerts", R"({"dir":"even","min":255,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["ETARI","PIKIL"],"route":["T420 TNT UL28 PENIL M144 BAGSO ERNAN NIBOG"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGWU_C140_alerts", R"({"dir":"even","min":255,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["T420 TNT UL28 PENIL UL70 BAGSO ERNAN NIBOG"]})", true, false},
    AlertCase{"EGWU_C141_alerts", R"({"dir":"even","min":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL","RESNO","VENER"],"route":["T420 TNT UL28 PENIL DEJEM OZRAT WETFI REVNU"]})", true, false},
    AlertCase{"EGWU_C142_alerts", R"({"dir":"odd","min":195,"max":245,"nodests":["EG","EI"],"points":["KLONN"],"route":["T420 TNT N57 POL N601 GRICE P600 ADN LESNI P600 OVDAN"]})", true, false},
    AlertCase{"EGWU_C143_alerts", R"({"dir":"odd","min":255,"max":195,"nodests":["EG","EI"],"points":["KLONN"],"route":["T420 TNT N57 POL N601 GRICE P600 BUDON"]})", true, false},
    AlertCase{"EGWU_C144_alerts", R"({"dir":"any","min":295,"nodests":["EG","EI"],"points":["WETFI"],"route":["T420 TNT UL28 PENIL DEJEM OZRAT"]})", true, false},
    AlertCase{"EGXT_C0_alerts", R"({"dir":"odd","min":245,"max":155,"dests":["EGWU"],"nodests":["EG","EI"],"route":["BKY LAM"]})", true, false},
    AlertCase{"EGXW_C0_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["ADODO","NALAN","OSBON","PEMOS","ETILO"],"route":["NATEB N610 VEREX","NATEB N97 TLA"]})", true, false},
    AlertCase{"EGXW_C1_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["AGORI"],"route":["OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO IBROD","OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO MIMKU"]})", true, false},
    AlertCase{"EGXW_C2_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["ATSIX","BALIX","ORTAV"],"route":["NATEB N610 VEREX"]})", true, false},
    AlertCase{"EGXW_C3_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["BILTO"],"route":["OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO MIMKU"]})", true, false},
    AlertCase{"EGXW_C4_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["ERAKA"],"route":["NATEB N97 TLA"]})", true, false},
    AlertCase{"EGXW_C5_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["ETARI"],"route":["OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO KUGUR","OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO NIBOG"]})", true, false},
    AlertCase{"EGXW_C6_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["PIKIL"],"route":["OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO APSOV","OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO MIMKU","OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO NIBOG"]})", true, false},
    AlertCase{"EGXW_C7_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["RATSU"],"route":["NATEB N610 VEREX BARKU"]})", true, false},
    AlertCase{"EGXW_C8_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["RESNO"],"route":["OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO LUTOV","OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO NIBOG"]})", true, false},
    AlertCase{"EGXW_C9_alerts", R"({"dir":"even","min":255,"nodests":["EG","EI"],"points":["SUNOT"],"route":["OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO AMLAD","OTR GOLES Y70 BATLI UY250 RIMTO L46 GETNO MIMKU"]})", true, false},
    AlertCase{"EGXW_C10_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES UL975 DESIG UL70"]})", true, false},
    AlertCase{"EGXW_C11_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES UL975 DESIG UL70 GUNTU Z196 LELDO M145"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C12_alerts", R"({"dir":"even","min":245,"dests":["EIDG","EIDW","EIME","EIWT"],"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES UL975 DESIG UL70 GUNTU Z196 LELDO M145"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGXW_C13_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C14_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["BAGSO"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C15_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["BANBA","SLANY"],"route":["PEDIG FELCA OFSOX"]})", true, false},
    AlertCase{"EGXW_C16_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["DOGAL","NEBIN"],"route":["OTR GOLES UL975 DESIG UL70 BAGSO"]})", true, false},
    AlertCase{"EGXW_C17_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["DOGAL","NEBIN"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C18_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["DOGAL","NEBIN"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C19_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES UL975 DESIG UL70 BAGSO"]})", true, false},
    AlertCase{"EGXW_C20_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES UL975 DESIG UL70 GUNTU Z196 LELDO M145 BAGSO"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C21_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES UL975 DESIG UL70 GUNTU Z196 LELDO M145 BAGSO"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGXW_C22_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C23_alerts", R"({"dir":"even","min":245,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C24_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["GAPLI"],"route":["MAM TR1 LND","MAM TR1 VLN GITUS"]})", true, false},
    AlertCase{"EGXW_C25_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["LESLU"],"route":["MAM BKY LAM L980 MID L620 SAM N19 ADKIK FONZU"]})", true, false},
    AlertCase{"EGXW_C26_alerts", R"({"dir":"even","min":245,"nodests":["EG","EI"],"points":["MOPAT"],"route":["MAM BKY LAM L980 MID L620 SAM N19 ADKIK"]})", true, false},
    AlertCase{"EGXW_C27_alerts", R"({"dir":"even","min":245,"max":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES L975 DESIG L70"]})", true, false},
    AlertCase{"EGXW_C28_alerts", R"({"dir":"even","min":245,"max":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES L975 DESIG L70 GUNTU Z196 LELDO M145"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C29_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EIDG","EIDW","EIME","EIWT"],"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES L975 DESIG L70 GUNTU Z196 LELDO M145"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGXW_C30_alerts", R"({"dir":"even","min":245,"max":245,"nodests":["EG","EI"],"points":["BAGSO"],"route":["OTR GOLES L975 DESIG L70 PENIL M144"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C31_alerts", R"({"dir":"even","min":245,"max":245,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["BAGSO"],"route":["OTR GOLES L975 DESIG L70 PENIL M144"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C32_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES L975 DESIG L70 BAGSO"]})", true, false},
    AlertCase{"EGXW_C33_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES L975 DESIG L70 PENIL L28 LELDO M145 BAGSO"],"alerts":[{"srd":457,"note":"Reroute via M144","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C34_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES L975 DESIG L70 PENIL L28 LELDO M145 BAGSO"],"restrictions":[{"alt":["Reroute via M144"],"types":["J"]}]})", true, false},
    AlertCase{"EGXW_C35_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EIDW"],"nodests":["EG","EI"],"route":["OTR GOLES L975 DESIG L70 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C36_alerts", R"({"dir":"even","min":245,"max":245,"dests":["EIDW"],"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"route":["OTR GOLES L975 DESIG L70 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C37_alerts", R"({"dir":"even","min":245,"max":245,"nodests":["EG","EI"],"points":["ENJEX"],"route":["PEDIG BCN P4 FELCA L9 OFSOX N83"]})", true, false},
    AlertCase{"EGXW_C38_alerts", R"({"dir":"even","min":245,"max":245,"nodests":["EG","EI"],"points":["SLANY"],"route":["PEDIG BCN P4 FELCA L9"]})", true, false},
    AlertCase{"EGXW_C39_alerts", R"({"dir":"odd","min":245,"max":195,"dests":["EGWU"],"nodests":["EG","EI"],"route":["TNT HON"]})", true, false},
    AlertCase{"EGXW_C40_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["OTR GOLES UL975 DESIG UL70 BAGSO REVNU"]})", true, false},
    AlertCase{"EGXW_C41_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO REVNU"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C42_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["ETARI","PIKIL"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO REVNU"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C43_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["RESNO"],"route":["OTR GOLES UL975 DESIG UL70 BAGSO","OTR GOLES UL975 DESIG UL70 BAGSO REVNU"]})", true, false},
    AlertCase{"EGXW_C44_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["RESNO"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO","OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO REVNU"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C45_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["RESNO"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO","OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO REVNU"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C46_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["VENER"],"route":["OTR GOLES UL975 DESIG UL70 BAGSO"]})", true, false},
    AlertCase{"EGXW_C47_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI"],"points":["VENER"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C48_alerts", R"({"dir":"even","min":245,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["VENER"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C49_alerts", R"({"dir":"even","min":255,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["OTR GOLES UL975 DESIG UL70 BAGSO ERNAN NIBOG"]})", true, false},
    AlertCase{"EGXW_C50_alerts", R"({"dir":"even","min":255,"max":295,"nodests":["EG","EI"],"points":["ETARI","PIKIL"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO ERNAN NIBOG"],"alerts":[{"srd":455,"note":"Reroute via M145","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C51_alerts", R"({"dir":"even","min":255,"max":295,"nodests":["EG","EI","EIDG","EIDW","EIME","EIWT"],"points":["ETARI","PIKIL"],"route":["OTR GOLES UL975 DESIG UL70 PENIL M144 BAGSO ERNAN NIBOG"],"restrictions":[{"alt":["Reroute via M145"],"types":["J"],"start":{"time":"0630"},"end":{"time":"2230"}}]})", true, false},
    AlertCase{"EGXW_C52_alerts", R"({"dir":"even","min":255,"max":285,"nodests":["EG","EI"],"points":["GOMUP"],"route":["SUPEL Y70 ABTOS N110 AGPED Y96 TLA"]})", true, false},
    AlertCase{"EGXW_C53_alerts", R"({"dir":"even","min":285,"nodests":["EG","EI"],"points":["GOMUP"],"route":["SUPEL Y70 ABTOS N110 ERKIT L602 TLA"]})", true, false},
    AlertCase{"EGXW_C54_alerts", R"({"dir":"odd","min":255,"nodests":["EG","EI"],"points":["GOREV","PETIL"],"route":["TIPTA UP17 DIGBI P15 GIVEM SURAT"]})", true, false},
    AlertCase{"EGXW_C55_alerts", R"({"dir":"odd","min":255,"nodests":["EG","EI"],"points":["NIVUN"],"route":["TIPTA UP17 DIGBI P15 GIVEM LAMRO"]})", true, false},
    AlertCase{"EGXW_C56_alerts", R"({"dir":"odd","min":255,"nodests":["EG","EI"],"points":["TINAC"],"route":["TIPTA UP17 DIGBI P15 GIVEM ITSUX"]})", true, false},
    AlertCase{"EGXW_C57_alerts", R"({"dir":"odd","min":255,"nodests":["EG","EI"],"points":["VAXIT"],"route":["TIPTA UP17 DIGBI P15 GIVEM REKNA"]})", true, false},
    AlertCase{"EGXW_C58_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["KONAN"],"route":["MAM CLN M189 DVR UL9"]})", true, false},
    AlertCase{"EGXW_C59_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LAMSO"],"route":["OTBED Y70 SUPEL L90 DOLAS L603"]})", true, false},
    AlertCase{"EGXW_C60_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["MAM BKY LAM L980 MID L620 SAM M195 MARUK N621","MAM BKY LAM L980 MID L620 SAM N63"]})", true, false},
    AlertCase{"EGXW_C61_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["MAM BKY LAM L980 MID L620 SAM N621"],"alerts":[{"srd":272,"note":"reroute via LORKU","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C62_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LELNA"],"nopoints":["QPR"],"route":["MAM BKY LAM L980 MID L620 SAM N621"],"restrictions":[{"alt":["reroute via LORKU"]}],"alerts":[{"srd":272,"note":"If after leaving the UK the aircraft routes via QPR, it must re-file using a route that exits UK at LORKU.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGXW_C63_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"route":["MAM BKY LAM L980 MID L620 SAM M195"]})", true, false},
    AlertCase{"EGXW_C64_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"route":["MAM BKY LAM L980 MID L620 SAM N621 MARUK M195"],"alerts":[{"srd":271,"note":"reroute via LELNA","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C65_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LORKU"],"nopoints":["ARE","DIN"],"route":["MAM BKY LAM L980 MID L620 SAM N621 MARUK M195"],"restrictions":[{"alt":["reroute via LELNA"]}],"alerts":[{"srd":271,"note":"If after leaving the UK the aircraft routes via ARE or DIN, it must re-file using a route that exits UK at LELNA.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGXW_C66_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["REDFA"],"route":["BANEM SONDO M183"]})", true, false},
    AlertCase{"EGXW_C67_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["SITET"],"route":["MAM UMBAG LAM L980 MID L151"]})", true, false},
    AlertCase{"EGXW_C68_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["SOMVA"],"route":["MAM BANEM P155"]})", true, false},
    AlertCase{"EGXW_C69_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["XAMAB"],"route":["MAM BKY LAM L980 MID UL612"]})", true, false},
    AlertCase{"EGXW_C70_alerts", R"({"dir":"odd","min":245,"max":245,"nodests":["EG","EI"],"points":["KONAN"],"route":["MAM CLN M189 DVR L9"]})", true, false},
    AlertCase{"EGXW_C71_alerts", R"({"dir":"odd","min":175,"max":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["MAM BKY LAM Q3 OCK MID L620 SAM N63"]})", true, false},
    AlertCase{"EGXW_C72_alerts", R"({"dir":"odd","min":175,"max":245,"nodests":["EG","EI"],"points":["SITET"],"route":["MAM BKY LAM Q3 OCK MID L151"]})", true, false},
    AlertCase{"EGXW_C73_alerts", R"({"dir":"odd","min":175,"max":245,"nodests":["EG","EI"],"points":["XAMAB"],"route":["MAM BKY LAM Q3 OCK MID L612"]})", true, false},
    AlertCase{"EGXW_C74_alerts", R"({"dir":"odd","min":175,"max":245,"nodests":["EG","EI"],"points":["XIDIL"],"route":["MAM BKY WEZKO CPT N859 GWC Y8 WAFFU M605"]})", true, false},
    AlertCase{"EGXW_C75_alerts", R"({"dir":"odd","min":195,"max":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["MAM BKY LAM Q3 OCK MID L620 SAM M195 MARUK N621"]})", true, false},
    AlertCase{"EGXW_C76_alerts", R"({"dir":"odd","min":195,"max":245,"nodests":["EG","EI"],"points":["LELNA"],"route":["MAM BKY LAM Q3 OCK MID L620 SAM N621"]})", true, false},
    AlertCase{"EGXW_C77_alerts", R"({"dir":"even","min":175,"max":245,"nodests":["EG","EI"],"points":["MOLIX"],"route":["OTBED Y70 BODSO L17"]})", true, false},
    AlertCase{"EGXW_C78_alerts", R"({"dir":"even","min":295,"nodests":["EG","EI"],"points":["PIKIL","RESNO","VENER"],"route":["OTR GOLES UL975 DESIG UL70 PENIL DEJEM OZRAT WETFI REVNU"]})", true, false},
    AlertCase{"EGXW_C79_alerts", R"({"dir":"odd","min":245,"max":155,"dests":["LFAC","LFAQ","LFAT","LFAV","LFAY","LFQQ","LFQO","LFQT","LA","LD","LO","LT","LG","HE","LC","LIPZ"],"nodests":["EG","EI"],"points":["RINTI"],"route":["MAM CLN M189 DVR L10"],"alerts":[{"srd":480,"note":"SRD in error and NATs has been notified. Route has been modified to work with Vatsim.","warn":true,"ban":false}]})", true, true},
    AlertCase{"EGXW_C80_alerts", R"({"dir":"odd","min":245,"max":155,"nodests":["EG","EI"],"points":["RINTI"],"route":["MAM CLN M189 DVR L10"],"alerts":[{"srd":480,"note":"","warn":false,"ban":true}]})", false, false},
    AlertCase{"EGXW_C81_alerts", R"({"dir":"odd","min":245,"max":115,"nodests":["EG","EI"],"points":["SUMUM"],"route":["MAM WTZ CLN L608"]})", true, false},
    AlertCase{"EGXW_C82_alerts", R"({"dir":"any","min":295,"nodests":["EG","EI"],"points":["WETFI"],"route":["OTR GOLES UL975 DESIG UL70 PENIL DEJEM OZRAT"]})", true, false},
    AlertCase{"EGXW_C83_alerts", R"({"dir":"odd","min":245,"max":175,"nodests":["EG","EI"],"points":["XIDIL"],"route":["MAM BKY DET M604 LYD M189 WAFFU M605"]})", true, false},
    AlertCase{"EGYD_C0_alerts", R"({"dir":"odd","min":215,"dests":["EGNJ"],"nodests":["EG","EI"],"route":["TNT M868 ADELU UPTON L975 GOLES"]})", true, false},
    AlertCase{"EGYD_C1_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNM"],"nodests":["EG","EI"],"route":["TNT N57 DENBY LBA"]})", true, false},
    AlertCase{"EGYD_C2_alerts", R"({"dir":"even","min":255,"max":245,"dests":["EGNM"],"nodests":["EG","EI"],"route":["TNT N57 TIPIL LBA"]})", true, false},
    AlertCase{"EGYD_C3_alerts", R"({"dir":"even","min":255,"max":195,"dests":["EGNV"],"nodests":["EG","EI"],"route":["TNT N57 POL P18 GASKO"]})", true, false},
    AlertCase{"EGYD_C4_alerts", R"({"dir":"odd","min":125,"max":195,"dests":["EGSS"],"nodests":["EG","EI"],"route":["TNT HON L15 FINMA"]})", true, false},
    AlertCase{"EGYD_C5_alerts", R"({"dir":"odd","min":245,"max":125,"dests":["EGSS"],"nodests":["EG","EI"],"route":["TNT HON FINMA"]})", true, false},
    AlertCase{"EGYD_C6_alerts", R"({"dir":"odd","min":245,"max":195,"dests":["EGWU"],"nodests":["EG","EI"],"route":["TNT HON"]})", true, false},
    AlertCase{"EGYD_C7_alerts", R"({"dir":"odd","min":155,"max":245,"nodests":["EG","EI"],"points":["KONAN"],"route":["TNT HON L15 BIG L9"]})", true, false},
    AlertCase{"EGYD_C8_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["KONAN"],"route":["TNT HON L15 BIG UL9"]})", true, false},
    AlertCase{"EGYD_C9_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["LAMSO"],"route":["OTBED Y70 SUPEL L90 DOLAS L603"]})", true, false},
    AlertCase{"EGYD_C10_alerts", R"({"dir":"odd","min":245,"nodests":["EG","EI"],"points":["SITET"],"route":["TNT HON UN859"]})", true, false},
    AlertCase{"EGYD_C11_alerts", R"({"dir":"odd","min":305,"nodests":["EG","EI"],"points":["SITET"],"route":["TNT HON"],"restrictions":[{"start":{"time":"0601"},"end":{"time":"0600"}}]})", true, false},
    AlertCase{"EGYD_C12_alerts", R"({"dir":"odd","min":305,"nodests":["EG","EI"],"points":["KONAN"],"route":["TNT HON L15 FINMA CHT ITVIP"]})", true, false},
    AlertCase{"EGYD_C13_alerts", R"({"dir":"odd","min":245,"max":155,"nodests":["EG","EI"],"points":["KONAN"],"route":["TNT PEDIG M605 DTY L10 BPK N601 DET L6 DVR L9"]})", true, false},
    AlertCase{"EGYD_C14_alerts", R"({"dir":"even","min":185,"max":245,"nodests":["EG","EI"],"points":["MOLIX"],"route":["OTBED Y70 BODSO L17"]})", true, false},
    AlertCase{"EGYD_C15_alerts", R"({"dir":"odd","min":165,"nodests":["EG","EI"],"points":["REDFA"],"route":["BANEM SONDO M183"]})", true, false},
    AlertCase{"EGYD_C16_alerts", R"({"dir":"odd","min":245,"max":245,"nodests":["EG","EI"],"points":["SITET"],"route":["TNT HON N859"]})", true, false}
), [](const ::testing::TestParamInfo<AlertCase>& i){ return std::string(i.param.id); });

