name: Add issues to vFPC Development Tracker

on:
  issues:
    types: [opened]

permissions:
  repository-projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh project item-add 26 --owner VFPC --url "${{ github.event.issue.html_url }}"
